"""Add amenities column to all the table

Revision ID: b41ad69ef002
Revises: cb31e754707b
Create Date: 2024-04-25 06:26:48.769153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41ad69ef002'
down_revision = 'cb31e754707b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jva_lga', sa.String(length=255), nullable=False))

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_lga', sa.String(length=255), nullable=False))

    with op.batch_alter_table('shared', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_lga', sa.String(length=255), nullable=False))

    with op.batch_alter_table('short_let', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shortlet_lga', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('short_let', schema=None) as batch_op:
        batch_op.drop_column('shortlet_lga')

    with op.batch_alter_table('shared', schema=None) as batch_op:
        batch_op.drop_column('shared_lga')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('property_lga')

    with op.batch_alter_table('jva', schema=None) as batch_op:
        batch_op.drop_column('jva_lga')

    # ### end Alembic commands ###
