"""Add amenities column to Shared table

Revision ID: cb31e754707b
Revises: 
Create Date: 2024-04-19 08:59:23.172920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb31e754707b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amenities', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared', schema=None) as batch_op:
        batch_op.drop_column('amenities')

    # ### end Alembic commands ###
